#!/usr/bin/env python3

"""
Xingyu Yan
xingyuyan@outlook.com
27-01-2020
"""

import datetime
import click
from PyPDF4 import PdfFileReader, PdfFileWriter

@click.command()
@click.argument("pdffile", type = click.Path(exists = True))
@click.argument("start", type = click.INT)
@click.argument("end", type = click.INT)
@click.option("--out", "-o", "outfile", prompt = "out put", default = "sliced")
def slice(pdffile, start, end, outfile):
    """
    Slice certain range of original PDF file, [start, end], inclusive.\n
        pdffile: the original file\n
        start: start page, counting from 1\n
        end: end page\n
        outfile: the default output file is "sliced-localtime.pdf"\n
    """
    fh = open(pdffile, "rb")
    reader = PdfFileReader(fh)

    if end < start or start < 1 or end > reader.numPages:
        raise Exception("Slicing out of range!")

    writer = PdfFileWriter()
    
    for x in range(start - 1, end):
        writer.addPage(reader.getPage(x))

    fs = open(outfile + "-" + datetime.datetime.now().__str__() + ".pdf", "wb")
    writer.write(fs)

    fh.close()
    fs.close()

if __name__ == "__main__":
    slice()
